FROM python:3.11-slim

# TODO: install mininet, impacket system deps, openvswitch
RUN apt-get update && apt-get install -y --no-install-recommends \
    iproute2 iputils-ping \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY pyproject.toml ./
COPY src ./src
RUN pip install --no-cache-dir -e .

CMD ["python", "-m", "adapt.orchestrator"]
