services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  sandbox:
    build:
      context: ..
      dockerfile: docker/Dockerfile.sandbox
    privileged: true # required for Mininet network namespaces
    depends_on:
      - ollama

  telemetry:
    build:
      context: ..
      dockerfile: docker/Dockerfile.telemetry
    privileged: true # required for eBPF kernel probes and Sysmon-for-Linux
    depends_on:
      - sandbox

  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8082:80"

volumes:
  ollama_data:
